# Generated by Django 4.2 on 2023-04-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='converted_to_client',
            field=models.BooleanField(default=False),
        ),
    ]
