# Generated by Django 4.2 on 2023-04-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0002_prospect_converted_to_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(max_length=25, verbose_name='Prénom'),
        ),
    ]
