# Generated by Django 4.2 on 2023-05-15 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CRM', '0003_alter_lead_sales_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client'},
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': 'Contrat'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Évènement'},
        ),
        migrations.AlterModelOptions(
            name='eventstatus',
            options={'verbose_name': 'Status', 'verbose_name_plural': 'Status'},
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={'verbose_name': 'Prospect'},
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='sales_contact',
            field=models.ForeignKey(default=None, limit_choices_to={'role': 'Vente'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='amount',
            field=models.FloatField(verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='payement_due',
            field=models.DateField(verbose_name="Date d'échéance"),
        ),
        migrations.AlterField(
            model_name='contract',
            name='sales_contact',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.IntegerField(verbose_name='Nombre de participants'),
        ),
        migrations.AlterField(
            model_name='event',
            name='client',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='CRM.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='event',
            name='contract',
            field=models.ForeignKey(limit_choices_to={'status': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='CRM.contract', verbose_name='Contrat'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(verbose_name="Date de l'évènement"),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRM.eventstatus', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='event',
            name='note',
            field=models.TextField(max_length=500, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='event',
            name='support_contact',
            field=models.ForeignKey(limit_choices_to={'role': 'Support'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='eventstatus',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Initiateur'),
        ),
        migrations.AlterField(
            model_name='eventstatus',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Intitulé'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='converted_to_client',
            field=models.BooleanField(default=False, verbose_name='Converti en client'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='first_name',
            field=models.CharField(max_length=25, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='last_name',
            field=models.CharField(max_length=25, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='mobile',
            field=models.CharField(max_length=10, verbose_name='Tél. mobile'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(max_length=10, verbose_name='Tél. fixe'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='sales_contact',
            field=models.ForeignKey(limit_choices_to={'role': 'Vente'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Contact'),
        ),
    ]
