# Generated by Django 4.2 on 2023-05-16 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0004_alter_client_options_alter_contract_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventstatus',
            name='creator',
        ),
    ]
