# Generated by Django 4.2 on 2023-04-23 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0005_eventstatus_client_company_name_lead_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventstatus',
            name='status',
            field=models.CharField(choices=[('En préparation', 'En préparation'), ('En cours', 'En cours'), ('Terminé', 'Terminé')], default='En préparation', max_length=20),
        ),
    ]
