# Generated by Django 4.2 on 2023-05-16 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CRM', '0007_alter_lead_sales_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='sales_contact',
            field=models.ForeignKey(default=None, limit_choices_to=models.Q(('role', 'Vente'), ('role', 'Gestion'), _connector='OR'), on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='event',
            name='support_contact',
            field=models.ForeignKey(limit_choices_to=models.Q(('role', 'Support'), ('role', 'Gestion'), _connector='OR'), on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='sales_contact',
            field=models.ForeignKey(limit_choices_to=models.Q(('role', 'Vente'), ('role', 'Gestion'), _connector='OR'), on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Contact'),
        ),
    ]
