# Generated by Django 4.2 on 2023-04-23 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0007_event_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='assigned',
            field=models.BooleanField(default=False, verbose_name='Assigné'),
        ),
        migrations.AlterField(
            model_name='event',
            name='contract',
            field=models.ForeignKey(blank=True, default=None, limit_choices_to={'status': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='CRM.contract'),
        ),
    ]
