# Generated by Django 4.2 on 2023-04-24 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0008_contract_assigned_alter_event_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='contract',
            field=models.ForeignKey(blank=True, default=None, limit_choices_to={'assigned': False, 'status': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='CRM.contract'),
        ),
    ]
