# Generated by Django 4.2 on 2023-04-25 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CRM', '0009_alter_event_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='sales_contact',
            field=models.ForeignKey(default=None, limit_choices_to={'role': 'Vente'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
