# Generated by Django 4.2 on 2023-04-26 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0010_alter_lead_sales_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventstatus',
            name='status',
        ),
    ]
