# Generated by Django 4.2 on 2023-05-03 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CRM', '0011_remove_eventstatus_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='assigned',
        ),
        migrations.AlterField(
            model_name='client',
            name='sales_contact',
            field=models.ForeignKey(default=None, limit_choices_to={'role': 'Vente'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
