# Generated by Django 4.2 on 2023-05-04 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0013_alter_event_contract_alter_event_support_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='contract',
            field=models.ForeignKey(limit_choices_to={'status': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='CRM.contract'),
        ),
    ]
