# Generated by Django 4.2 on 2023-05-15 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Collaborateur', 'verbose_name_plural': 'Collaborateurs'},
        ),
    ]
