# Generated by Django 4.2 on 2023-04-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_customuser_is_active_alter_customuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[(1, 'Gestion'), (2, 'Vente'), (3, 'Support')], max_length=10, null=True),
        ),
    ]
